name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Pack Viscacha CLI
      run: dotnet pack src/Viscacha.CLI/Viscacha.CLI.csproj --configuration Release --no-build --output nupkg

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nupkg
        path: nupkg/*.nupkg

